id: I982551B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:16:36+00:00'
last_modified: '2022-06-08T13:17:49.688641+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5243
  title: སྒྲུབ་པའི་གནས་མཆོག་ཡེར་པའི་དཀར་ཆག་དད་པའི་ས་བོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DAA4:
      image_group_id: I3CN5245
      title: ''
      total_pages: 54
      order: 1
      base_file: DAA4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
