id: I982551B0
legacy_id: P010397
ocr_import_info:
  bdrc_scan_id: W3CN5243
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T23:16:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:54:11.445608+00:00'
last_modified: 2022-09-03 22:54:16.250723
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5243
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5243
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲུབ་པའི་གནས་མཆོག་ཡེར་པའི་དཀར་ཆག་དད་པའི་ས་བོན།
statistics:
  ocr_word_mean_confidence_index: 0.9189089111642499
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5245:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5245
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5245.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9189089111642499
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
